# pages/privacy_policy.py
import dash
from dash import html, callback, Input, Output

dash.register_page(
    __name__,
    path="/privacy_policy",
    name="Privacy Policy"
)

layout = html.Div(
    [
        # Body content placeholder (will fill via callback)
        html.Div(id="privacy-policy-body-content", style={"flex": 1}),

        # Footer always at bottom, full‑width
        html.Footer(
            children=[
                html.Hr(),
                html.Div(
                    [
                        html.P(
                            "This Page Is NOT DoD Affiliated. I am just an NCO who got tired of remaking excels to speculate about points.",
                            className="mb-0",
                            style={"color": "yellow"},
                        ),
                        html.P(
                            "Contact: PromotionPointDashboard@gmail.com",
                            className="mb-0",
                            style={"color": "yellow"},
                        ),
                        html.P("© 2025 Army Promotion Point Dashboard", className="mb-0", style={"color": "yellow"}),
                    ],
                    className="text-center"
                ),
                html.Div(style={"height": "40px"})
            ],
            style={
                "backgroundColor": "#013220",
                "padding": "0px",
                "width": "100%",
            }
        ),
    ],
    style={
        "display": "flex",
        "flexDirection": "column",
        "minHeight": "100vh",
    }
)

@callback(
    Output("privacy-policy-body-content", "children"),
    Input("dark-mode-store", "data"),
    allow_duplicate=True
)
def update_privacy_policy_text(is_dark):
    text_color = "white" if is_dark else "black"
    return html.Div(
        [
            html.H1(
                "Privacy Policy",
                style={
                    "color": "gold",
                    "textAlign": "center",
                    "fontFamily": "Georgia, serif",
                    "marginBottom": "0.5em",
                }
            ),

            html.P(
                "Last updated: April 21, 2025",
                style={
                    "textAlign": "center",
                    "color": text_color,
                    "fontStyle": "italic",
                    "fontSize": "18px",
                    "marginBottom": "2em",
                    "fontFamily": "Arial, sans-serif",
                }
            ),
            html.P(
                "This Privacy Policy describes our policies and procedures on the collection, use, and disclosure "
                "of your information when you use the Service and tells you about your privacy rights and how the "
                "law protects you.",
                style={
                    "fontSize": "18px",
                    "marginBottom": "1.5em",
                    "lineHeight": "1.6",
                    "color": text_color,
                }
            ),
            html.P(
                [
                    "I do not want, nor do I personally collect your data. The following privacy policy is generated "
                    "based on the services I use to host this website (Cloudflare and Railway). It was created with the "
                    "help of the free ",
                    html.A(
                        "Privacy Policy Generator",
                        href="https://www.privacypolicies.com/privacy-policy-generator/",
                        target="_blank",
                        style={"color": "green", "textDecoration": "underline", "fontSize": "18px"},
                    ),
                    " service. All details following this explanation are generated by this service. "
                    "By using this site, you agree to any collection and use of information in accordance "
                    "with this Privacy Policy."
                ],
                style={
                    "fontSize": "18px",
                    "marginBottom": "2em",
                    "lineHeight": "1.6",
                    "color": text_color,
                }
            ),

            html.H2("Interpretation and Definitions", style={"color": "green", "marginTop": "2em", "fontFamily": "Georgia, serif"}),

            html.H3("Interpretation", style={"marginTop": "1em", "fontFamily": "Georgia, serif"}),
            html.P(
                "The words in which the initial letter is capitalized have meanings defined under the following conditions. These definitions apply whether they appear in singular or plural.",
                style={
                    "fontSize": "18px",
                    "marginBottom": "1.5em",
                    "lineHeight": "1.6",
                    "color": text_color,
                }
            ),

            html.H3("Definitions", style={"marginTop": "1em", "fontFamily": "Georgia, serif"}),
            html.P(
                "For the purposes of this Privacy Policy:",
                style={
                    "fontSize": "18px",
                    "marginBottom": "1em",
                    "lineHeight": "1.6",
                    "color": text_color,
                }
            ),
            html.Ul(
                [
                    html.Li([html.Strong("Account:"), html.Span(" a unique account created for you to access our Service.", style={"fontSize": "18px", "color": text_color})]),
                    html.Li([html.Strong("Affiliate:"), html.Span(" an entity controlling, controlled by, or under common control with a party.", style={"fontSize": "18px", "color": text_color})]),
                    html.Li([html.Strong("Company:"), html.Span(" refers to Army Promotion Point Dashboard.", style={"fontSize": "18px", "color": text_color})]),
                    html.Li([html.Strong("Cookies:"), html.Span(" small files placed on your device containing browsing information.", style={"fontSize": "18px", "color": text_color})]),
                    html.Li([html.Strong("Country:"), html.Span(" refers to Hawaii, United States.", style={"fontSize": "18px", "color": text_color})]),
                    html.Li([html.Strong("Device:"), html.Span(" any device that can access the Service.", style={"fontSize": "18px", "color": text_color})]),
                    html.Li([html.Strong("Personal Data:"), html.Span(" any information relating to an identified individual.", style={"fontSize": "18px", "color": text_color})]),
                    html.Li([html.Strong("Service:"), html.Span(" refers to the Website.", style={"fontSize": "18px", "color": text_color})]),
                    html.Li([html.Strong("Service Provider:"), html.Span(" third-party companies processing data for the Company.", style={"fontSize": "18px", "color": text_color})]),
                    html.Li([html.Strong("Usage Data:"), html.Span(" data collected automatically through the Service.", style={"fontSize": "18px", "color": text_color})]),
                    html.Li([
                        html.Strong("Website:"),
                        html.Span(" refers to Army Promotion Point Dashboard, accessible from ", style={"fontSize": "18px", "color": text_color}),
                        html.A("https://promotionpointdashboard.com/", href="https://promotionpointdashboard.com/", target="_blank", style={"color": "green", "textDecoration": "underline", "fontSize": "18px"})
                    ]),
                    html.Li([html.Strong("You:"), html.Span(" the individual accessing the Service, or the company/entity they represent.", style={"fontSize": "18px", "color": text_color})]),
                ],
                style={"marginBottom": "2em", "lineHeight": "1.6"}
            ),

            html.H2("Collecting and Using Your Personal Data", style={"color": "green", "marginTop": "2em", "fontFamily": "Georgia, serif"}),
            html.H3("Types of Data Collected", style={"marginTop": "1em", "fontFamily": "Georgia, serif"}),

            html.H4("Personal Data", style={"marginTop": "0.5em", "fontFamily": "Georgia, serif"}),
            html.P(
                "While using our Service, we may ask you to provide certain personally identifiable information. Personally identifiable information may include Usage Data.",
                style={
                    "fontSize": "18px",
                    "marginBottom": "1em",
                    "lineHeight": "1.6",
                    "color": text_color,
                }
            ),

            html.H4("Usage Data", style={"marginTop": "1em", "fontFamily": "Georgia, serif"}),
            html.P(
                "Usage Data is collected automatically when using the Service and may include your device’s IP address, browser type, pages visited, and more.",
                style={
                    "fontSize": "18px",
                    "marginBottom": "1.5em",
                    "lineHeight": "1.6",
                    "color": text_color,
                }
            ),

            html.H4("Tracking Technologies and Cookies", style={"marginTop": "1em", "fontFamily": "Georgia, serif"}),
            html.P(
                "We use Cookies and similar tracking technologies such as beacons, tags, and scripts to track activities and improve our Service.",
                style={
                    "fontSize": "18px",
                    "marginBottom": "0.5em",
                    "lineHeight": "1.6",
                    "color": text_color,
                }
            ),
            html.Ul(
                [
                    html.Li([html.Strong("Cookies or Browser Cookies:"), html.Span(" small files placed on your device.", style={"fontSize": "18px", "color": text_color})]),
                    html.Li([html.Strong("Web Beacons:"), html.Span(" tiny electronic files to monitor user behavior and site performance.", style={"fontSize": "18px", "color": text_color})]),
                ],
                style={"marginBottom": "1.5em", "lineHeight": "1.6"}
            ),

            html.H4("Use of Your Personal Data", style={"marginTop": "1em", "fontFamily": "Georgia, serif"}),
            html.P(
                "We may use Personal Data to provide, manage, and improve the Service, communicate updates, and for legal compliance.",
                style={
                    "fontSize": "18px",
                    "marginBottom": "2em",
                    "lineHeight": "1.6",
                    "color": text_color,
                }
            ),

            html.H3("Sharing Your Personal Information", style={"marginTop": "2em", "fontFamily": "Georgia, serif"}),
            html.Ul(
                [
                    html.Li([html.Strong("With Service Providers:"), html.Span(" for analytics and contact purposes.", style={"fontSize": "18px", "color": text_color})]),
                    html.Li([html.Strong("For Business Transfers:"), html.Span(" if assets are sold, Personal Data may transfer.", style={"fontSize": "18px", "color": text_color})]),
                    html.Li([html.Strong("With Affiliates:"), html.Span(" controlled under this Privacy Policy.", style={"fontSize": "18px", "color": text_color})]),
                    html.Li([html.Strong("With Business Partners:"), html.Span(" for promotions.", style={"fontSize": "18px", "color": text_color})]),
                    html.Li([html.Strong("With Other Users:"), html.Span(" information you share publicly may be seen by others.", style={"fontSize": "18px", "color": text_color})]),
                    html.Li([html.Strong("With Your Consent:"), html.Span(" for other uses with your permission.", style={"fontSize": "18px", "color": text_color})]),
                ],
                style={"marginBottom": "2em", "lineHeight": "1.6"}
            ),

            html.H3("Security of Your Personal Data", style={"marginTop": "2em", "fontFamily": "Georgia, serif"}),
            html.P(
                "We strive to use commercially acceptable means to protect your Personal Data but cannot guarantee absolute security.",
                style={
                    "fontSize": "18px",
                    "marginBottom": "2em",
                    "lineHeight": "1.6",
                    "color": text_color,
                }
            ),

            html.H2("Children’s Privacy", style={"marginTop": "2em", "fontFamily": "Georgia, serif"}),
            html.P(
                "Our Service does not address anyone under the age of 13. We do not knowingly collect personal data from anyone under 13.",
                style={
                    "fontSize": "18px",
                    "marginBottom": "2em",
                    "lineHeight": "1.6",
                    "color": text_color,
                }
            ),

            html.H2("Links to Other Websites", style={"marginTop": "2em", "fontFamily": "Georgia, serif"}),
            html.P(
                "We are not responsible for the content, privacy policies, or practices of any third‑party sites or services.",
                style={
                    "fontSize": "18px",
                    "marginBottom": "2em",
                    "lineHeight": "1.6",
                    "color": text_color,
                }
            ),

            html.H2("Changes to This Privacy Policy", style={"marginTop": "2em", "fontFamily": "Georgia, serif"}),
            html.P(
                "We may update our Privacy Policy from time to time. Changes are effective once posted on this page.",
                style={
                    "fontSize": "18px",
                    "marginBottom": "2em",
                    "lineHeight": "1.6",
                    "color": text_color,
                }
            ),

            html.H2("Contact Us", style={"marginTop": "2em", "fontFamily": "Georgia, serif"}),
            html.P(
                [
                    "If you have any questions about this Privacy Policy, you can contact us via email at ",
                    html.A(
                        "promotionpointdashboard@gmail.com",
                        href="mailto:promotionpointdashboard@gmail.com",
                        style={"textDecoration": "underline", "fontSize": "18px", "color": text_color},
                    ),
                    ".",
                ],
                style={
                    "fontSize": "18px",
                    "marginBottom": "2em",
                    "lineHeight": "1.6",
                    "color": text_color,
                }
            ),
        ],
        style={
            "marginLeft": "4in",
            "marginRight": "4in",
            "paddingTop": "30px",
            "paddingBottom": "30px",
            "fontFamily": "Arial, sans-serif",
        }
    )
